name: CI/CD

on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

env:
  PROJECT_ID: good-united
  GCP_SA: etl-325@good-united.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Typescript
        run: tsc --sourceMap false

      - name: Copy lock files
        run: |
          cp package.json dist/package.json
          cp package-lock.json dist/package-lock.json

      - name: Set env vars (dev)
        if: endsWith(github.ref, '/dev')
        run: |
          echo "FUNCTION_NAME=good-united-fb-ads-insights-dev" >> $GITHUB_ENV
          echo "PUBLIC_URL=https://us-central1-good-united.cloudfunctions.net/good-united-fb-ads-insights-dev" >> $GITHUB_ENV

      - name: Set env vars (prod)
        if: endsWith(github.ref, '/master')
        run: |
          echo "FUNCTION_NAME=good-united-fb-ads-insights" >> $GITHUB_ENV
          echo "PUBLIC_URL=https://us-central1-good-united.cloudfunctions.net/good-united-fb-ads-insights" >> $GITHUB_ENV

      - name: Auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Deploy
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: ${{ env.FUNCTION_NAME }}
          entry_point: main
          source_dir: dist
          runtime: nodejs16
          memory_mb: 2048MB,
          timeout: 530,
          service_account_email: ${{ env.GCP_SA }}
          env_vars: GCP_SA=${{ env.GCP_SA }},PROJECT_ID=${{ env.PROJECT_ID }},PUBLIC_URL=${{ env.PUBLIC_URL }},ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }},API_KEY=${{ secrets.API_KEY }},MONGO_URI=${{ secrets.MONGO_URI }}
